### ISSUE TITLE
Fail to run on Linux Mint 17.3 (Ubuntu 14.04)

### ISSUE THREAD

**Issue by Napsty** [pablodav/sharepoint_health_mon_plugin#1]
Tried to install it using the pip3 commands. Once setuptools was upgraded, I was able to install sp-health:

```
# pip3 install sp-health --upgrade
Downloading/unpacking sp-health
  Downloading sp_health-0.2.2-py3-none-any.whl
Requirement already up-to-date: rstcheck in /usr/local/lib/python3.4/dist-packages (from sp-health)
Requirement already up-to-date: shareplum in /usr/local/lib/python3.4/dist-packages (from sp-health)
Requirement already up-to-date: docutils>=0.7 in /usr/local/lib/python3.4/dist-packages (from rstcheck->sp-health)
Installing collected packages: sp-health
Successfully installed sp-health
Cleaning up..
```

But when I try to run sphealth:
```

$ sphealth --help
/usr/local/lib/python3.4/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.7.1) or chardet (2.2.1) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/local/bin/sphealth", line 7, in <module>
    from sharepoint_health.__main__ import main
  File "/usr/local/lib/python3.4/dist-packages/sharepoint_health/__main__.py", line 5, in <module>
    from .plugin_check import HealthMonitor
  File "/usr/local/lib/python3.4/dist-packages/sharepoint_health/plugin_check.py", line 2, in <module>
    from shareplum import Site
  File "/usr/local/lib/python3.4/dist-packages/shareplum/__init__.py", line 9, in <module>
    from .shareplum import *
  File "/usr/local/lib/python3.4/dist-packages/shareplum/shareplum.py", line 4, in <module>
    import requests
  File "/usr/local/lib/python3.4/dist-packages/requests/__init__.py", line 90, in <module>
    from urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'
```

Can you add some requirements on the README.md and how to resolve them?

**Comment by pablodav** [comment]
Hi, thanks for reporting.

I'm using this on Ubuntu 14.04, so it should work.

Looks like the `requests` package should be upgraded.

I have replicated the issue and found this to solve it as workaround:

`sudo pip3 install -U requests`

I'm will add minimun requirement for requests in file `requirements.txt`, and will publish it as "fix" for next version, so for new installation it will be solved.

**Comment by Napsty** [comment]
```
# sudo pip3 install -U requests
Requirement already up-to-date: requests in /usr/local/lib/python3.4/dist-packages
Cleaning up...
```
So looks like I already have the latest version of requests.

```
# sudo pip3 list|grep requests
requests (2.18.4)
```

Any other hint?

> will add minimun requirement for requests in file requirements.txt

Yes, that's a great idea. Thanks.

**Comment by pablodav** [comment]
So it didn't work for you?

**Comment by Napsty** [comment]
FYI i was able to successfully build and install the plugin (manually). But unable to install via pip3.
```

python3 setup.py build
sudo python3 setup.py install
```

```
$ sphealth --help
usage: sphealth [-h] [-u [USER]] [-p [PASSWORD]] [-s [SITE_URL]]

optional arguments:
  -h, --help            show this help message and exit
  -u [USER], --user [USER]
                        Username for Ntlm auth like domain\user 
  -p [PASSWORD], --password [PASSWORD]
                        Password for Ntlm Auth like  
  -s [SITE_URL], --site [SITE_URL]
                        site url for sharepoint HealthMonitor, ex: http://site:9876 
```

**Comment by pablodav** [comment]
Very strange, ok I will upload latest package to pypi and if the problem appear again you can reopen it.

**Comment by pablodav** [comment]
package uploaded to pip, version 0.2.3

**Comment by Napsty** [comment]
Looks better. Thanks a lot.

```
# pip3 install sp-health --upgrade
Downloading/unpacking sp-health from https://pypi.python.org/packages/6b/0e/6d16c2ae6204b7a794f548e4f0aa8b24b43b3a68139612126226f0b51dc3/sp_health-0.2.3-py3-none-any.whl#md5=d93f303c4c51052c4e9cb1e696014015
  Downloading sp_health-0.2.3-py3-none-any.whl
Requirement already up-to-date: requests>=2.18.4 in /usr/local/lib/python3.4/dist-packages (from sp-health)
Requirement already up-to-date: SharePlum>=0.1.1 in /usr/local/lib/python3.4/dist-packages (from sp-health)
Requirement already up-to-date: rstcheck>=3.1 in /usr/local/lib/python3.4/dist-packages (from sp-health)
Requirement already up-to-date: docutils>=0.7 in /usr/local/lib/python3.4/dist-packages (from rstcheck>=3.1->sp-health)
Installing collected packages: sp-health
  Found existing installation: sp-health 0.2.2
    Uninstalling sp-health:
      Successfully uninstalled sp-health
Successfully installed sp-health
Cleaning up...

 
# sphealth --help
usage: sphealth [-h] [-u [USER]] [-p [PASSWORD]] [-s [SITE_URL]]

optional arguments:
  -h, --help            show this help message and exit
  -u [USER], --user [USER]
                        Username for Ntlm auth like domain\user 
  -p [PASSWORD], --password [PASSWORD]
                        Password for Ntlm Auth like  
  -s [SITE_URL], --site [SITE_URL]
                        site url for sharepoint HealthMonitor, ex: http://site:9876 
```
